// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _ky_KY = {
  "bottomNavText1": "Башкы",
  "bottomNavText2": "Жаңылыктар",
  "bottomNavText3": "Байланыштар",
  "bottomNavText4": "Жөндөөлөр",
  "mainPageTitle": "Менин эсептерим",
  "mainPageNoCheck": "Кошулган эсептер жок",
  "mainPageNoCheckDesc": "Эсептерди көрүү жана кызматтарды башкаруу үчүн жеке эсепти кошуңуз",
  "mainPageAddCheck": "Эсеп кошуу",
  "mainPageWhereToFind": "Жеке эсеп номерин кайдан табууга болот?",
  "mainPageShowed": "Жеке эсеп номери квитанцияда көрсөтүлгөн",
  "activate": "Иштетүү",
  "settingApp": "Колдонмону өз каалооңузга ылайык жөндөнүңүз",
  "notifications": "Билдирмелер",
  "seeAllNotifications": "Бардык билдирмелер окулду",
  "aboutApp": "Колдонмо жөнүндө",
  "pravaSecured": "© 2026 Бардык укуктар корголгон",
  "themeApp": "Колдонмонун темасы",
  "langInterface": "Интерфейстин тили",
  "themeLight": "Ачык",
  "themeDark": "Караңгы",
  "themeSystem": "Системалык",
  "splashSubTitle": "Жеке эсептерди башкаруу",
  "configurationLoading": "Конфигурацияны жүктөө...",
  "version": "Версия",
  "splashTitle": "Манас Тазалык",
  "contactAddress": "Дарек",
  "contactManasAddress": "г. Манас, Манас көч., 92",
  "contactAbonent": "Абоненттик бөлүм",
  "contactManasAbonentSubtitle": "0 (3722) 5-16-29",
  "contactDispatchers": "Диспетчерлер",
  "contactManasDispatchersSubtitle": "0997303103 Самат",
  "contactTechnical": "Техникалык бөлүм",
  "contactManasTechnicalSubtitle": "5-21-72 Динара",
  "contactEmail": "Электрондук почта",
  "contactManasEmailSubtitle": "abon.otdeltazalyk@mail.ru, tazalykkg@mail.ru",
  "contactInstagram": "Instagram",
  "contactManasInstagramSubtitle": "tazalyk_manas",
  "accountNumberHint": "Жеке эсеп номери",
  "appTitle": "Манас Тазалык",
  "welcomeTitle": "Кош келиңиз!",
  "welcomeSubtitle": "Эсептерди көрүү жана кызматтарды башкаруу үчүн жеке эсеп номерин киргизиңиз",
  "langKyrgyz": "Кыргызча",
  "langRussian": "Орусча",
  "langEnglish": "Англисче",
  "addButton": "Кошуу",
  "notificationDefaultTitle": "Жаңы билдирме",
  "scannerTitle": "Сканер",
  "scannerInstruction": "Камераны QR-кодго же штрих-кодго багыттаңыз",
  "scannerAccountSearch": "Жеке эсептин издөөсү",
  "scannerAccountSearchDesc": "Сканер 8 сандык номурду автоматтык түрдө табат",
  "scannerSelectFromGallery": "Галереядан тандоо",
  "scannerNoCodeFound": "QR-код же штрих-код табылган жок",
  "accountsSection": "Эсептер",
  "accountsCount": "{{count}} эсеп",
  "toPay": "Төлөөгө",
  "accountLabel": "ЖЭ",
  "fullNameLabel": "Аты-жөнү",
  "addressLabel": "Дарек",
  "registered": "Катталган",
  "residing": "Жашайт",
  "updateDate": "Жаңыртуу датасы",
  "accountDetails": "Подробнее о счете",
  "accrualHistory": "История начислений",
  "deleteAccount": "Удалить счет",
  "tapForDetails": "Толук маалымат үчүн басыңыз",
  "serviceTypeHousehold": "Үй",
  "payButton": "Төлөө",
  "printInvoice": "Чек басып чыгаруу",
  "history": "Тарых",
  "noNotifications": "Билдирмелер жок",
  "noNotificationsDesc": "Маанилүү билдирмелер жана жаңыртуулар бул жерде көрсөтүлөт",
  "historyNoData": "Тарых боюнча маалымат жок",
  "historyChargesForPeriod": "Мезгил үчүн эсептөөлөр",
  "historyPeriod": "Мезгил",
  "historyCharges": "Эсептөөлөр",
  "historyServices": "Кызматтар",
  "historyNoServicesData": "Кызматтар боюнча маалымат жок",
  "historyTotal": "Жыйынтык:",
  "historyPeriodStart": "Мезгилдин башы",
  "historyAccrued": "Эсептелди",
  "historyPaid": "Төлөндү",
  "historyPeriodEnd": "Мезгилдин аягы",
  "historyVolume": "Көлөм",
  "historyCubicMeters": "Куб метр",
  "historyTariff": "Тариф",
  "historyAmount": "Суммасы",
  "historyTax": "НСП",
  "currencySom": "сом",
  "unitPeople": "адам",
  "unitCubicMeters": "м³",
  "detailPageTitle": "Эсептин маалыматы",
  "detailPersonalAccount": "Жеке эсеп",
  "serviceTypeCommercial": "Коммерция",
  "overpayment": "Ашыкча төлөм",
  "detailAtPeriodStart": "Мезгилдин башына",
  "taxes": "Салыктар",
  "lastPayment": "Акыркы төлөм",
  "controller": "Контролёр",
  "paymentSuccessTitle": "Төлөм ийгиликтүү",
  "paymentSuccessMessage": "Төлөм ийгиликтүү аткарылды.",
  "okButton": "Ок",
  "chargesAndPayments": "Эсептөөлөр жана төлөмдөр",
  "lastThreeMonths": "Акыркы үч ай үчүн "
};
static const Map<String,dynamic> _en_US = {
  "bottomNavText1": "Home",
  "bottomNavText2": "News",
  "bottomNavText3": "Contacts",
  "bottomNavText4": "Settings",
  "mainPageTitle": "My Bills",
  "mainPageNoCheck": "No accounts added",
  "mainPageNoCheckDesc": "Add an account to view bills and manage services",
  "mainPageAddCheck": "Add Account",
  "mainPageWhereToFind": "Where to find account number?",
  "mainPageShowed": "Account number is shown on your receipt",
  "activate": "Иштетүү",
  "settingApp": "Customize the app to your preferences",
  "notifications": "Notifications",
  "seeAllNotifications": "All notifications read",
  "aboutApp": "About app",
  "pravaSecured": "© 2026 All rights reserved",
  "themeApp": "App theme",
  "langInterface": "Interface Language",
  "themeLight": "Light",
  "themeDark": "Dark",
  "themeSystem": "System",
  "splashSubTitle": "Manage your accounts",
  "configurationLoading": "Loading Configuration...",
  "version": "Version",
  "splashTitle": "Manas Tazalyk",
  "contactAddress": "Address",
  "contactManasAddress": "Manas, Manas St., 92",
  "contactAbonent": "Customer Service",
  "contactManasAbonentSubtitle": "0 (3722) 5-16-29",
  "contactDispatchers": "Dispatchers",
  "contactManasDispatchersSubtitle": "0997303103 Samat",
  "contactTechnical": "Technical Department",
  "contactManasTechnicalSubtitle": "5-21-72 Dinara",
  "contactEmail": "Email",
  "contactManasEmailSubtitle": "abon.otdeltazalyk@mail.ru, tazalykkg@mail.ru",
  "contactInstagram": "Instagram",
  "contactManasInstagramSubtitle": "tazalyk_manas",
  "accountNumberHint": "Account number",
  "appTitle": "Manas Tazalyk",
  "welcomeTitle": "Welcome!",
  "welcomeSubtitle": "Enter your account number to view bills and manage services",
  "langKyrgyz": "Kyrgyz",
  "langRussian": "Russian",
  "langEnglish": "English",
  "addButton": "Add",
  "notificationDefaultTitle": "New notification",
  "scannerTitle": "Scanner",
  "scannerInstruction": "Point the camera at the QR code or barcode",
  "scannerAccountSearch": "Account search",
  "scannerAccountSearchDesc": "Scanner will automatically find the 8-digit number",
  "scannerSelectFromGallery": "Select from gallery",
  "scannerNoCodeFound": "QR code or barcode not found",
  "accountsSection": "Accounts",
  "accountsCount": "{{count}} account",
  "toPay": "To pay",
  "accountLabel": "Account",
  "fullNameLabel": "Full name",
  "addressLabel": "Address",
  "registered": "Registered",
  "residing": "Residing",
  "updateDate": "Update date",
  "tapForDetails": "Tap for details",
  "serviceTypeHousehold": "Household",
  "payButton": "Pay",
  "printInvoice": "Print invoice",
  "history": "History",
  "noNotifications": "No notifications",
  "accountDetails": "Account details",
  "accrualHistory": "Accrual history",
  "deleteAccount": "Delete account",
  "noNotificationsDesc": "Important notifications and updates will be shown here",
  "historyNoData": "No history data",
  "historyChargesForPeriod": "Charges for the period",
  "historyPeriod": "Period",
  "historyCharges": "Charges",
  "historyServices": "Services",
  "historyNoServicesData": "No service data",
  "historyTotal": "Total:",
  "historyPeriodStart": "Period start",
  "historyAccrued": "Accrued",
  "historyPaid": "Paid",
  "historyPeriodEnd": "Period end",
  "historyVolume": "Volume",
  "historyCubicMeters": "Cubic meters",
  "historyTariff": "Tariff",
  "historyAmount": "Amount",
  "historyTax": "Tax",
  "currencySom": "som",
  "unitPeople": "people",
  "unitCubicMeters": "m³",
  "detailPageTitle": "Account details",
  "detailPersonalAccount": "Personal account",
  "serviceTypeCommercial": "Commercial",
  "overpayment": "Overpayment",
  "detailAtPeriodStart": "At period start",
  "taxes": "Taxes",
  "lastPayment": "Last payment",
  "controller": "Controller",
  "paymentSuccessTitle": "Payment successful",
  "paymentSuccessMessage": "The payment was completed successfully.",
  "okButton": "OK",
  "chargesAndPayments": "Charges and Payments",
  "lastThreeMonths": "For the last three months"
};
static const Map<String,dynamic> _ru_RU = {
  "bottomNavText1": "Главная",
  "bottomNavText2": "Новости",
  "bottomNavText3": "Контакты",
  "bottomNavText4": "Настройки",
  "mainPageTitle": "Мои счета",
  "mainPageNoCheck": "Нет добавленных счетов",
  "mainPageNoCheckDesc": "Добавьте лицевой счет для просмотра счетов и управления услугами",
  "mainPageAddCheck": "Добавить счет",
  "mainPageWhereToFind": "Где найти номер лицевого счета?",
  "mainPageShowed": "Номер лицевого счета указан в квитанции",
  "activate": "Иштетүү",
  "settingApp": "Настройте приложение под свои предпочтения",
  "notifications": "Уведомления",
  "seeAllNotifications": "Все уведомления прочитаны",
  "aboutApp": "О приложении",
  "pravaSecured": "© 2026 Все права защищены",
  "themeApp": "Тема приложения",
  "langInterface": "Язык интерфейса",
  "themeLight": "Светлая",
  "themeDark": "Темная",
  "themeSystem": "Системная",
  "splashSubTitle": "Управление личными счетами",
  "configurationLoading": "Загрузка конфигурации...",
  "version": "Версия",
  "splashTitle": "Манас Тазалык",
  "contactAddress": "Адрес",
  "contactManasAddress": "г. Манас, ул. Манас 92",
  "contactAbonent": "Абонентский отдел",
  "contactManasAbonentSubtitle": "0 (3722) 5-16-29",
  "contactDispatchers": "Диспетчеры",
  "contactManasDispatchersSubtitle": "0997303103 Самат",
  "contactTechnical": "Технический отдел",
  "contactManasTechnicalSubtitle": "5-21-72 Динара",
  "contactEmail": "Электронная почта",
  "contactManasEmailSubtitle": "abon.otdeltazalyk@mail.ru, tazalykkg@mail.ru",
  "contactInstagram": "Instagram",
  "contactManasInstagramSubtitle": "tazalyk_manas",
  "accountNumberHint": "Номер лицевого счета",
  "appTitle": "Манас Тазалык",
  "welcomeTitle": "Добро пожаловать!",
  "welcomeSubtitle": "Укажите номер лицевого счета для доступа к счетам и управления услугами",
  "langKyrgyz": "Кыргызча",
  "langRussian": "Русский",
  "langEnglish": "English",
  "addButton": "Добавить",
  "notificationDefaultTitle": "Новое уведомление",
  "scannerTitle": "Сканер",
  "scannerInstruction": "Наведите камеру на QR-код или штрих-код",
  "scannerAccountSearch": "Поиск лицевого счета",
  "scannerAccountSearchDesc": "Сканер автоматически найдет 8-значный номер",
  "scannerSelectFromGallery": "Выбрать из галереи",
  "scannerNoCodeFound": "QR-код или штрих-код не найден",
  "accountsSection": "Счета",
  "accountsCount": "{{count}} счет",
  "toPay": "К оплате",
  "accountLabel": "ЛС",
  "fullNameLabel": "ФИО",
  "addressLabel": "Адрес",
  "registered": "Зарегистрировано",
  "residing": "Проживают",
  "updateDate": "Дата обновления",
  "tapForDetails": "Нажмите для деталей",
  "serviceTypeHousehold": "Быт",
  "payButton": "Оплатить",
  "printInvoice": "Печать счета",
  "history": "История",
  "noNotifications": "Нет уведомлений",
  "accountDetails": "Подробнее о счете",
  "accrualHistory": "История начислений",
  "deleteAccount": "Удалить счет",
  "noNotificationsDesc": "Здесь будут показаны важные уведомления и обновления",
  "historyNoData": "Нет данных по истории",
  "historyChargesForPeriod": "Начисления за период",
  "historyPeriod": "Период",
  "historyCharges": "Начисления",
  "historyServices": "Услуги",
  "historyNoServicesData": "Нет данных по услугам",
  "historyTotal": "Итого:",
  "historyPeriodStart": "Начало периода",
  "historyAccrued": "Начислено",
  "historyPaid": "Оплачено",
  "historyPeriodEnd": "Конец периода",
  "historyVolume": "Объем",
  "historyCubicMeters": "Кубометры",
  "historyTariff": "Тариф",
  "historyAmount": "Сумма",
  "historyTax": "НСП",
  "currencySom": "сом",
  "unitPeople": "адам/чел.",
  "unitCubicMeters": "м³",
  "detailPageTitle": "Детали счета",
  "detailPersonalAccount": "Лицевой счет",
  "serviceTypeCommercial": "Ком",
  "overpayment": "Переплата",
  "detailAtPeriodStart": "На начало периода",
  "taxes": "Налоги",
  "lastPayment": "Последний платеж",
  "controller": "Контролер",
  "paymentSuccessTitle": "Оплата успешна",
  "paymentSuccessMessage": "Платеж успешно выполнен.",
  "okButton": "Ок",
  "chargesAndPayments": "Начисления и оплаты",
  "lastThreeMonths": "За последние "
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ky_KY": _ky_KY, "en_US": _en_US, "ru_RU": _ru_RU};
}
